[phases.setup]
nixPkgs = ['python3', 'pip']

[phases.install]
cmd = 'pip install -r requirements.txt'

[start]
cmd = 'gunicorn --bind=0.0.0.0:$PORT --workers=1 --worker-class=eventlet --timeout=30 app:app'